general {
    lock_cmd = pidof hyprlock || hyprlock --config ~/.config/hypr/hyprlock.conf
}

listener {
    timeout = 10
    on-timeout = brightnessctl -sd asus::kbd_backlight set 0
    on-resume = brightnessctl -rd asus::kbd_backlight
}
